// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice = BlogSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogpostsDocumentDataSlicesSlice = BlogpostsSlice;

/**
 * Content for BlogPosts documents
 */
interface BlogpostsDocumentData {
  /**
   * Slice Zone field in *BlogPosts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogpostsDocumentDataSlicesSlice>;
}

/**
 * BlogPosts document from Prismic
 *
 * - **API ID**: `blogposts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostsDocumentData>,
    "blogposts",
    Lang
  >;

type ContactPageDocumentDataSlicesSlice = ContactSlice;

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
  /**
   * Slice Zone field in *Contact Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactPageDocumentData>,
    "contact_page",
    Lang
  >;

type HomeDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | CertificationsSlice
  | ExperienceSlice
  | SkillsSlice
  | ProjectsSlice
  | EducationSlice
  | AboutSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * NID field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].n_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  n_id: prismic.KeyTextField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Component field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].component
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  component: prismic.KeyTextField;

  /**
   * Description field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | BlogpostsDocument
  | ContactPageDocument
  | HomeDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Mission field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.mission
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  mission: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Blog → Default → Primary → Posts*
 */
export interface BlogSliceDefaultPrimaryPostsItem {
  /**
   * Posts field in *Blog → Default → Primary → Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.posts[].posts
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  posts: prismic.ContentRelationshipField<"blogposts">;
}

/**
 * Primary content in *Blog → Default → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * Posts field in *Blog → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.posts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  posts: prismic.GroupField<Simplify<BlogSliceDefaultPrimaryPostsItem>>;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Item in *BlogPosts → Default → Primary → Tags*
 */
export interface BlogpostsSliceDefaultPrimaryTagsItem {
  /**
   * Tag field in *BlogPosts → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *BlogPosts → Default → Primary*
 */
export interface BlogpostsSliceDefaultPrimary {
  /**
   * Title field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Excerpt field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Content field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Tags field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<BlogpostsSliceDefaultPrimaryTagsItem>>;

  /**
   * Publish Date field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposts.default.primary.publish_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField;
}

/**
 * Default variation for BlogPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogpostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogpostsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPosts*
 */
type BlogpostsSliceVariation = BlogpostsSliceDefault;

/**
 * BlogPosts Shared Slice
 *
 * - **API ID**: `blogposts`
 * - **Description**: Blog Posts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogpostsSlice = prismic.SharedSlice<
  "blogposts",
  BlogpostsSliceVariation
>;

/**
 * Default variation for CertificationCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationCollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CertificationCollection*
 */
type CertificationCollectionSliceVariation =
  CertificationCollectionSliceDefault;

/**
 * CertificationCollection Shared Slice
 *
 * - **API ID**: `certification_collection`
 * - **Description**: CertificationCollection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationCollectionSlice = prismic.SharedSlice<
  "certification_collection",
  CertificationCollectionSliceVariation
>;

/**
 * Item in *Certifications → Default → Primary → Certification*
 */
export interface CertificationsSliceDefaultPrimaryCertificationItem {}

/**
 * Primary content in *Certifications → Default → Primary*
 */
export interface CertificationsSliceDefaultPrimary {
  /**
   * Certification field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.certification[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  certification: prismic.GroupField<
    Simplify<CertificationsSliceDefaultPrimaryCertificationItem>
  >;

  /**
   * Cert Name field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Certification title
   * - **API ID Path**: certifications.default.primary.cert_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cert_name: prismic.KeyTextField;

  /**
   * Cert Acronym field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., "AWS SAA"
   * - **API ID Path**: certifications.default.primary.cert_acronym
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cert_acronym: prismic.KeyTextField;

  /**
   * Issuing Organization field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., "Amazon Web Services"
   * - **API ID Path**: certifications.default.primary.issuing_organization
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  issuing_organization: prismic.KeyTextField;

  /**
   * Issuer Logo field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.issuer_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  issuer_logo: prismic.ImageField<never>;

  /**
   * Cert Type field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.cert_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cert_type: prismic.SelectField<
    "Certification" | "License" | "Badge" | "Credentials (Micro)"
  >;

  /**
   * Cert Level field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.cert_level
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cert_level: prismic.SelectField<
    "Foundational" | "Associate" | "Professional" | "Expert" | "Specialty"
  >;

  /**
   * Issue Date field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: When earned
   * - **API ID Path**: certifications.default.primary.issue_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  issue_date: prismic.DateField;

  /**
   * Expiry Date field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: When it expires (if applicable)
   * - **API ID Path**: certifications.default.primary.expiry_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  expiry_date: prismic.DateField;

  /**
   * Is Lifetime field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: certifications.default.primary.is_lifetime
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_lifetime: prismic.BooleanField;

  /**
   * Credential ID field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Certificate number
   * - **API ID Path**: certifications.default.primary.credential_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  credential_id: prismic.KeyTextField;

  /**
   * Verification URL field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where to verify
   * - **API ID Path**: certifications.default.primary.verification_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  verification_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Certificate Image field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.certificate_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  certificate_image: prismic.ImageField<"certificate">;

  /**
   * Voice Summary field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: One-sentence description for voice
   * - **API ID Path**: certifications.default.primary.voice_summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  voice_summary: prismic.KeyTextField;

  /**
   * Achievement Keywords field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For search/voice commands
   * - **API ID Path**: certifications.default.primary.achievement_keywords
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  achievement_keywords: prismic.KeyTextField;

  /**
   * Credential Importance field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1-10 for AI prioritization
   * - **API ID Path**: certifications.default.primary.credential_importance
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  credential_importance: prismic.NumberField;
}

/**
 * Default variation for Certifications Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CertificationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Certifications*
 */
type CertificationsSliceVariation = CertificationsSliceDefault;

/**
 * Certifications Shared Slice
 *
 * - **API ID**: `certifications`
 * - **Description**: Certifications
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSlice = prismic.SharedSlice<
  "certifications",
  CertificationsSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Name field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Education → Default → Primary → Education*
 */
export interface EducationSliceDefaultPrimaryEducationItem {}

/**
 * Primary content in *Education → Default → Primary*
 */
export interface EducationSliceDefaultPrimary {
  /**
   * Education field in *Education → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.education[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  education: prismic.GroupField<
    Simplify<EducationSliceDefaultPrimaryEducationItem>
  >;

  /**
   * Institution Name field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: University/School name
   * - **API ID Path**: education.default.primary.institution_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  institution_name: prismic.KeyTextField;

  /**
   * Institution Logo field in *Education → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.institution_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  institution_logo: prismic.ImageField<never>;

  /**
   * Institution Location field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, Country
   * - **API ID Path**: education.default.primary.institution_location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  institution_location: prismic.KeyTextField;

  /**
   * Degree Type field in *Education → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.degree_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  degree_type: prismic.SelectField<
    "High School" | "Bachelor" | "Master" | "Diploma" | "Bootcamp" | "Course"
  >;

  /**
   * Degree Tilte field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., "Bachelor of Computer Science"
   * - **API ID Path**: education.default.primary.degree_tilte
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  degree_tilte: prismic.KeyTextField;

  /**
   * Field of Study field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., "Software Engineering"
   * - **API ID Path**: education.default.primary.field_of_study
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  field_of_study: prismic.KeyTextField;

  /**
   * Start Date field in *Education → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *Education → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Leave empty if ongoing
   * - **API ID Path**: education.default.primary.end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Is Current field in *Education → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: education.default.primary.is_current
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_current: prismic.BooleanField;

  /**
   * Graduation Year field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., "2022"
   * - **API ID Path**: education.default.primary.graduation_year
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  graduation_year: prismic.KeyTextField;

  /**
   * GPA Score field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: GPA/Percentage/Grade
   * - **API ID Path**: education.default.primary.gpa_score
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gpa_score: prismic.KeyTextField;

  /**
   * Thesis Title field in *Education → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Final year project/thesis
   * - **API ID Path**: education.default.primary.thesis_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  thesis_title: prismic.KeyTextField;

  /**
   * Thesis Description field in *Education → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Brief description
   * - **API ID Path**: education.default.primary.thesis_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  thesis_description: prismic.RichTextField;

  /**
   * Relevant Coursework field in *Education → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.relevant_coursework
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  relevant_coursework: prismic.SelectField<
    "Course Name" | "Course Code" | "Grade"
  >;

  /**
   * Key Achievements field in *Education → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Academic achievements
   * - **API ID Path**: education.default.primary.key_achievements
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  key_achievements: prismic.RichTextField;

  /**
   * Extracurriculars field in *Education → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Clubs, societies, activities
   * - **API ID Path**: education.default.primary.extracurriculars
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  extracurriculars: prismic.RichTextField;
}

/**
 * Default variation for Education Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EducationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Education*
 */
type EducationSliceVariation = EducationSliceDefault;

/**
 * Education Shared Slice
 *
 * - **API ID**: `education`
 * - **Description**: Education
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSlice = prismic.SharedSlice<
  "education",
  EducationSliceVariation
>;

/**
 * Default variation for EducationCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationCollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *EducationCollection*
 */
type EducationCollectionSliceVariation = EducationCollectionSliceDefault;

/**
 * EducationCollection Shared Slice
 *
 * - **API ID**: `education_collection`
 * - **Description**: EducationCollection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationCollectionSlice = prismic.SharedSlice<
  "education_collection",
  EducationCollectionSliceVariation
>;

/**
 * Item in *Experience → Default → Primary → Experience*
 */
export interface ExperienceSliceDefaultPrimaryExperienceItem {}

/**
 * Item in *Experience → Default → Primary → Key Achievements*
 */
export interface ExperienceSliceDefaultPrimaryKeyAchievementsItem {
  /**
   * Achievement Title field in *Experience → Default → Primary → Key Achievements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.key_achievements[].achievement_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  achievement_title: prismic.KeyTextField;

  /**
   * Achievement Description field in *Experience → Default → Primary → Key Achievements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.key_achievements[].achievement_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  achievement_description: prismic.RichTextField;

  /**
   * Metric Value field in *Experience → Default → Primary → Key Achievements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., "40% improvement"
   * - **API ID Path**: experience.default.primary.key_achievements[].metric_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metric_value: prismic.KeyTextField;

  /**
   * Impact Area field in *Experience → Default → Primary → Key Achievements*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.key_achievements[].impact_area
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  impact_area: prismic.SelectField<
    "Revenue" | "Cost" | "Efficiency" | "Quality" | "User-experience"
  >;
}

/**
 * Primary content in *Experience → Default → Primary*
 */
export interface ExperienceSliceDefaultPrimary {
  /**
   * Experience field in *Experience → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.experience[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  experience: prismic.GroupField<
    Simplify<ExperienceSliceDefaultPrimaryExperienceItem>
  >;

  /**
   * Company Name field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Employer name
   * - **API ID Path**: experience.default.primary.company_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;

  /**
   * Company Logo field in *Experience → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.company_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Company Website field in *Experience → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Company URL
   * - **API ID Path**: experience.default.primary.company_website
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  company_website: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Company Location field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, Country
   * - **API ID Path**: experience.default.primary.company_location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_location: prismic.KeyTextField;

  /**
   * Work Type field in *Experience → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.work_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  work_type: prismic.SelectField<
    | "Full-time"
    | "Part-time"
    | "Self-employed"
    | "Freelance"
    | "Contract"
    | "Internship"
    | "Apprenticeship"
    | "Volunteer"
  >;

  /**
   * Work Model field in *Experience → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.work_model
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  work_model: prismic.SelectField<"Onsite" | "Hybrid" | "Remote">;

  /**
   * Title field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Your position
   * - **API ID Path**: experience.default.primary.job_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_title: prismic.KeyTextField;

  /**
   * Department field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., "Engineering", "Product Development"
   * - **API ID Path**: experience.default.primary.department
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  department: prismic.KeyTextField;

  /**
   * Seniority Level field in *Experience → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.seniority_level
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  seniority_level: prismic.SelectField<
    | "Junior"
    | "Mid-level (Intermediate)"
    | "Senior"
    | "Lead"
    | "Principal"
    | "Manager"
    | "Director"
  >;

  /**
   * Start Date field in *Experience → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.startdate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  startdate: prismic.DateField;

  /**
   * End Date field in *Experience → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.enddate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  enddate: prismic.DateField;

  /**
   * Currently Work Here field in *Experience → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: experience.default.primary.is_current
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_current: prismic.BooleanField;

  /**
   * Role Summary field in *Experience → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Brief overview of the role
   * - **API ID Path**: experience.default.primary.role_summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role_summary: prismic.RichTextField;

  /**
   * Key Achievements field in *Experience → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.key_achievements[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  key_achievements: prismic.GroupField<
    Simplify<ExperienceSliceDefaultPrimaryKeyAchievementsItem>
  >;

  /**
   * Projects Delivered field in *Experience → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Number of projects completed
   * - **API ID Path**: experience.default.primary.projects_delivered
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  projects_delivered: prismic.NumberField;

  /**
   * Skills field in *Experience → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to skills page
   * - **API ID Path**: experience.default.primary.skills
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  skills: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Voice Summary field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: One-sentence role description
   * - **API ID Path**: experience.default.primary.voice_summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  voice_summary: prismic.KeyTextField;

  /**
   * Role Keyowords field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For search/voice commands
   * - **API ID Path**: experience.default.primary.role_keyowords
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role_keyowords: prismic.KeyTextField;

  /**
   * Impact Score field in *Experience → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1-10 for AI prioritization
   * - **API ID Path**: experience.default.primary.impact_score
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  impact_score: prismic.NumberField;
}

/**
 * Default variation for Experience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Experience*
 */
type ExperienceSliceVariation = ExperienceSliceDefault;

/**
 * Experience Shared Slice
 *
 * - **API ID**: `experience`
 * - **Description**: Experience
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSlice = prismic.SharedSlice<
  "experience",
  ExperienceSliceVariation
>;

/**
 * Default variation for ExperienceCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceCollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ExperienceCollection*
 */
type ExperienceCollectionSliceVariation = ExperienceCollectionSliceDefault;

/**
 * ExperienceCollection Shared Slice
 *
 * - **API ID**: `experience_collection`
 * - **Description**: ExperienceCollection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceCollectionSlice = prismic.SharedSlice<
  "experience_collection",
  ExperienceCollectionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Job Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.job_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_title: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Projects → Default → Primary → Project*
 */
export interface ProjectsSliceDefaultPrimaryProjectItem {}

/**
 * Item in *Projects → Default → Primary → Technologies*
 */
export interface ProjectsSliceDefaultPrimaryTechnologiesItem {
  /**
   * Tech Name field in *Projects → Default → Primary → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.technologies[].tech_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tech_name: prismic.KeyTextField;

  /**
   * Tech Category field in *Projects → Default → Primary → Technologies*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.technologies[].tech_category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tech_category: prismic.SelectField<
    "Frontend" | "Backend" | "Database" | "Dev-Ops"
  >;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Project field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.project[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project: prismic.GroupField<Simplify<ProjectsSliceDefaultPrimaryProjectItem>>;

  /**
   * Project Name field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project name
   * - **API ID Path**: projects.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project Slug field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: URL slug
   * - **API ID Path**: projects.default.primary.project_slug
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_slug: prismic.KeyTextField;

  /**
   * Project Tagline field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short one-liner description
   * - **API ID Path**: projects.default.primary.project_tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_tagline: prismic.KeyTextField;

  /**
   * Project Description field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed description
   * - **API ID Path**: projects.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * Project Status field in *Projects → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.project_status
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  project_status: prismic.SelectField<
    "Completed" | "In-progress" | "Maintained" | "Archived"
  >;

  /**
   * Start Date field in *Projects → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *Projects → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Featured Image field in *Projects → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Technologies field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.technologies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<ProjectsSliceDefaultPrimaryTechnologiesItem>
  >;

  /**
   * Live URL field in *Projects → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Live demo
   * - **API ID Path**: projects.default.primary.live_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  live_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * GitHub URL field in *Projects → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Repository
   * - **API ID Path**: projects.default.primary.github_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  github_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Client Name field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.client_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField;

  /**
   * Client Industry field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.client_industry
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_industry: prismic.KeyTextField;

  /**
   * Meta Title field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.meta_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.meta_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.og_image
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_image: prismic.KeyTextField;

  /**
   * Is Featured field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.is_featured
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  is_featured: prismic.KeyTextField;

  /**
   * Display Order field in *Projects → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.display_order
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  display_order: prismic.NumberField;

  /**
   * Color Scheme field in *Projects → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.color_scheme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  color_scheme: prismic.SelectField<"Cyan" | "Blue" | "Purple" | "Green">;

  /**
   * Voice Summary field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.voice_summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  voice_summary: prismic.KeyTextField;

  /**
   * AI Keywords field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.ai_keywords
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ai_keywords: prismic.KeyTextField;

  /**
   * Accessibility Notes field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.accessibility_notes
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  accessibility_notes: prismic.RichTextField;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Default variation for ProjectsCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsCollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProjectsCollection*
 */
type ProjectsCollectionSliceVariation = ProjectsCollectionSliceDefault;

/**
 * ProjectsCollection Shared Slice
 *
 * - **API ID**: `projects_collection`
 * - **Description**: ProjectsCollection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsCollectionSlice = prismic.SharedSlice<
  "projects_collection",
  ProjectsCollectionSliceVariation
>;

/**
 * Item in *Skills → Default → Primary → Skill*
 */
export interface SkillsSliceDefaultPrimarySkillItem {}

/**
 * Item in *Skills → Default → Primary → Related Projects*
 */
export interface SkillsSliceDefaultPrimaryRelatedProjectsItem {
  /**
   * Project Name field in *Skills → Default → Primary → Related Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.related_projects[].project_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_name: prismic.KeyTextField;

  /**
   * Project Link field in *Skills → Default → Primary → Related Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.related_projects[].project_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * Skill field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  skill: prismic.GroupField<Simplify<SkillsSliceDefaultPrimarySkillItem>>;

  /**
   * Skill Name field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_name: prismic.KeyTextField;

  /**
   * Skill Category field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  skill_category: prismic.SelectField<
    | "Frontend"
    | "Backend"
    | "Database"
    | "Dev-Ops"
    | "Tools"
    | "Design"
    | "Soft-skills"
  >;

  /**
   * Skill Type field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  skill_type: prismic.SelectField<
    "Language" | "Framework" | "Library" | "Tool" | "Platform" | "Methodology"
  >;

  /**
   * Proficiency Level field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.proficiency_level
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  proficiency_level: prismic.SelectField<
    "Beginner" | "Intermediate" | "Advanced" | "Expert"
  >;

  /**
   * Proficiency Percentage field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.proficiency_percentage
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  proficiency_percentage: prismic.NumberField;

  /**
   * Years Experience field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.years_experience
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  years_experience: prismic.NumberField;

  /**
   * Skill Icon field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_icon: prismic.KeyTextField;

  /**
   * Display Order field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.display_order
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  display_order: prismic.NumberField;

  /**
   * Colour Hex field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.colour_hex
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  colour_hex: prismic.KeyTextField;

  /**
   * Is Featured field in *Skills → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: skills.default.primary.is_featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_featured: prismic.BooleanField;

  /**
   * Skill Description field in *Skills → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: What you can do with this skill
   * - **API ID Path**: skills.default.primary.skill_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  skill_description: prismic.RichTextField;

  /**
   * Use Cases field in *Skills → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: How you've applied this skill
   * - **API ID Path**: skills.default.primary.use_cases
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  use_cases: prismic.RichTextField;

  /**
   * Certifications field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Related certifications
   * - **API ID Path**: skills.default.primary.certifications
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  certifications: prismic.KeyTextField;

  /**
   * Certification URL field in *Skills → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to certification
   * - **API ID Path**: skills.default.primary.certification_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  certification_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Projects Count field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Number of projects using this skill
   * - **API ID Path**: skills.default.primary.projects_count
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  projects_count: prismic.NumberField;

  /**
   * Related Projects field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.related_projects[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  related_projects: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimaryRelatedProjectsItem>
  >;

  /**
   * Professional Usage field in *Skills → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: How you've used it professionally
   * - **API ID Path**: skills.default.primary.professional_usage
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  professional_usage: prismic.RichTextField;

  /**
   * Learning Source field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**:  Where/how you learned it
   * - **API ID Path**: skills.default.primary.learning_source
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  learning_source: prismic.KeyTextField;

  /**
   * Currently Learning field in *Skills → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: skills.default.primary.currently_learning
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  currently_learning: prismic.BooleanField;

  /**
   * Next Milestone field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.next_milestone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  next_milestone: prismic.KeyTextField;

  /**
   * Voice Description field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description for voice reading
   * - **API ID Path**: skills.default.primary.voice_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  voice_description: prismic.KeyTextField;

  /**
   * Skill Keywords field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search/voice command keywords
   * - **API ID Path**: skills.default.primary.skill_keywords
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_keywords: prismic.KeyTextField;

  /**
   * Importance Rank field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1-10 for AI prioritization
   * - **API ID Path**: skills.default.primary.importance_rank
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  importance_rank: prismic.NumberField;

  /**
   * Skill Aliases field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Alternative names (e.g., "JS" for JavaScript)
   * - **API ID Path**: skills.default.primary.skill_aliases
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_aliases: prismic.KeyTextField;

  /**
   * Environment field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.environment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  environment: prismic.SelectField<
    "Client" | "Server" | "Fullstack" | "Mobile" | "Cloud"
  >;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

/**
 * Default variation for SkillsCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsCollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SkillsCollection*
 */
type SkillsCollectionSliceVariation = SkillsCollectionSliceDefault;

/**
 * SkillsCollection Shared Slice
 *
 * - **API ID**: `skills_collection`
 * - **Description**: SkillsCollection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsCollectionSlice = prismic.SharedSlice<
  "skills_collection",
  SkillsCollectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogpostsDocument,
      BlogpostsDocumentData,
      BlogpostsDocumentDataSlicesSlice,
      ContactPageDocument,
      ContactPageDocumentData,
      ContactPageDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      BlogSlice,
      BlogSliceDefaultPrimaryPostsItem,
      BlogSliceDefaultPrimary,
      BlogSliceVariation,
      BlogSliceDefault,
      BlogpostsSlice,
      BlogpostsSliceDefaultPrimaryTagsItem,
      BlogpostsSliceDefaultPrimary,
      BlogpostsSliceVariation,
      BlogpostsSliceDefault,
      CertificationCollectionSlice,
      CertificationCollectionSliceVariation,
      CertificationCollectionSliceDefault,
      CertificationsSlice,
      CertificationsSliceDefaultPrimaryCertificationItem,
      CertificationsSliceDefaultPrimary,
      CertificationsSliceVariation,
      CertificationsSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      EducationSlice,
      EducationSliceDefaultPrimaryEducationItem,
      EducationSliceDefaultPrimary,
      EducationSliceVariation,
      EducationSliceDefault,
      EducationCollectionSlice,
      EducationCollectionSliceVariation,
      EducationCollectionSliceDefault,
      ExperienceSlice,
      ExperienceSliceDefaultPrimaryExperienceItem,
      ExperienceSliceDefaultPrimaryKeyAchievementsItem,
      ExperienceSliceDefaultPrimary,
      ExperienceSliceVariation,
      ExperienceSliceDefault,
      ExperienceCollectionSlice,
      ExperienceCollectionSliceVariation,
      ExperienceCollectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimaryProjectItem,
      ProjectsSliceDefaultPrimaryTechnologiesItem,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      ProjectsCollectionSlice,
      ProjectsCollectionSliceVariation,
      ProjectsCollectionSliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimarySkillItem,
      SkillsSliceDefaultPrimaryRelatedProjectsItem,
      SkillsSliceDefaultPrimary,
      SkillsSliceVariation,
      SkillsSliceDefault,
      SkillsCollectionSlice,
      SkillsCollectionSliceVariation,
      SkillsCollectionSliceDefault,
    };
  }
}
