// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice = BlogSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type ContactPageDocumentDataSlicesSlice = ContactSlice;

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
  /**
   * Slice Zone field in *Contact Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactPageDocumentData>,
    "contact_page",
    Lang
  >;

type HomeDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | ExperienceSlice
  | SkillsSlice
  | ProjectsSlice
  | EducationSlice
  | AboutSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * NID field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].n_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  n_id: prismic.KeyTextField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Component field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].component
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  component: prismic.KeyTextField;

  /**
   * Description field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | ContactPageDocument
  | HomeDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Mission field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.mission
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  mission: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Blog → Default → Primary → Tags*
 */
export interface BlogSliceDefaultPrimaryTagsItem {
  /**
   * Tag field in *Blog → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *Blog → Default → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * Title field in *Blog → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Excerpt field in *Blog → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Content field in *Blog → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Tags field in *Blog → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<BlogSliceDefaultPrimaryTagsItem>>;

  /**
   * Publish Date field in *Blog → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.publish_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Name field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Default variation for Education Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Education*
 */
type EducationSliceVariation = EducationSliceDefault;

/**
 * Education Shared Slice
 *
 * - **API ID**: `education`
 * - **Description**: Education
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSlice = prismic.SharedSlice<
  "education",
  EducationSliceVariation
>;

/**
 * Primary content in *Experience → Default → Primary*
 */
export interface ExperienceSliceDefaultPrimary {
  /**
   * Title field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Employment Type field in *Experience → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.employment_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  employment_type: prismic.SelectField<
    | "Full-time"
    | "Part-time"
    | "Self-employed"
    | "Freelance"
    | "Contract"
    | "Internship"
    | "Apprenticeship"
    | "Volunteer"
  >;

  /**
   * Company or Organisation field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.employer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  employer: prismic.KeyTextField;

  /**
   * Currently Work Here field in *Experience → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: experience.default.primary.current
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  current: prismic.BooleanField;

  /**
   * Start Date field in *Experience → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.startdate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  startdate: prismic.DateField;

  /**
   * End Date field in *Experience → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.enddate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  enddate: prismic.DateField;

  /**
   * Location field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Location Type field in *Experience → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.location_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  location_type: prismic.SelectField<"Onsite" | "Hybrid" | "Remote">;

  /**
   * Description field in *Experience → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Experience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Experience*
 */
type ExperienceSliceVariation = ExperienceSliceDefault;

/**
 * Experience Shared Slice
 *
 * - **API ID**: `experience`
 * - **Description**: Experience
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExperienceSlice = prismic.SharedSlice<
  "experience",
  ExperienceSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Job Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.job_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_title: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Projects → Default → Primary → Technologies*
 */
export interface ProjectsSliceDefaultPrimaryTechnologiesItem {
  /**
   * Tech Name field in *Projects → Default → Primary → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.technologies[].tech_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tech_name: prismic.KeyTextField;

  /**
   * Tech Category field in *Projects → Default → Primary → Technologies*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.technologies[].tech_category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tech_category: prismic.SelectField<
    "Frontend" | "Backend" | "Database" | "Dev-Ops"
  >;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Project Name field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project name
   * - **API ID Path**: projects.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project Slug field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: URL slug
   * - **API ID Path**: projects.default.primary.project_slug
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_slug: prismic.KeyTextField;

  /**
   * Project Tagline field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short one-liner description
   * - **API ID Path**: projects.default.primary.project_tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_tagline: prismic.KeyTextField;

  /**
   * Project Description field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed description
   * - **API ID Path**: projects.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * Project Status field in *Projects → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.project_status
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  project_status: prismic.SelectField<
    "Completed" | "In-progress" | "Maintained" | "Archived"
  >;

  /**
   * Start Date field in *Projects → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *Projects → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Featured Image field in *Projects → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Technologies field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.technologies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<ProjectsSliceDefaultPrimaryTechnologiesItem>
  >;

  /**
   * Live URL field in *Projects → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Live demo
   * - **API ID Path**: projects.default.primary.live_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  live_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * GitHub URL field in *Projects → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Repository
   * - **API ID Path**: projects.default.primary.github_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  github_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Client Name field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.client_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField;

  /**
   * Client Industry field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.client_industry
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_industry: prismic.KeyTextField;

  /**
   * Meta Title field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.meta_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.meta_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.og_image
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_image: prismic.KeyTextField;

  /**
   * Is Featured field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.is_featured
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  is_featured: prismic.KeyTextField;

  /**
   * Display Order field in *Projects → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.display_order
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  display_order: prismic.NumberField;

  /**
   * Color Scheme field in *Projects → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.color_scheme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  color_scheme: prismic.SelectField<"Cyan" | "Blue" | "Purple" | "Green">;

  /**
   * Voice Summary field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.voice_summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  voice_summary: prismic.KeyTextField;

  /**
   * AI Keywords field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.ai_keywords
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ai_keywords: prismic.KeyTextField;

  /**
   * Accessibility Notes field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.accessibility_notes
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  accessibility_notes: prismic.RichTextField;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Item in *Skills → Default → Primary → Related Projects*
 */
export interface SkillsSliceDefaultPrimaryRelatedProjectsItem {
  /**
   * Project Name field in *Skills → Default → Primary → Related Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.related_projects[].project_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_name: prismic.KeyTextField;

  /**
   * Project Link field in *Skills → Default → Primary → Related Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.related_projects[].project_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * Skill Name field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_name: prismic.KeyTextField;

  /**
   * Skill Category field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  skill_category: prismic.SelectField<
    | "Frontend"
    | "Backend"
    | "Database"
    | "Dev-Ops"
    | "Tools"
    | "Design"
    | "Soft-skills"
  >;

  /**
   * Skill Type field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  skill_type: prismic.SelectField<
    "Language" | "Framework" | "Library" | "Tool" | "Platform" | "Methodology"
  >;

  /**
   * Proficiency Level field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.proficiency_level
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  proficiency_level: prismic.SelectField<
    "Beginner" | "Intermediate" | "Advanced" | "Expert"
  >;

  /**
   * Proficiency Percentage field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.proficiency_percentage
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  proficiency_percentage: prismic.NumberField;

  /**
   * Years Experience field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.years_experience
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  years_experience: prismic.NumberField;

  /**
   * Skill Icon field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skill_icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_icon: prismic.KeyTextField;

  /**
   * Display Order field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.display_order
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  display_order: prismic.NumberField;

  /**
   * Colour Hex field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.colour_hex
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  colour_hex: prismic.KeyTextField;

  /**
   * Is Featured field in *Skills → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: skills.default.primary.is_featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_featured: prismic.BooleanField;

  /**
   * Skill Description field in *Skills → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: What you can do with this skill
   * - **API ID Path**: skills.default.primary.skill_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  skill_description: prismic.RichTextField;

  /**
   * Use Cases field in *Skills → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: How you've applied this skill
   * - **API ID Path**: skills.default.primary.use_cases
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  use_cases: prismic.RichTextField;

  /**
   * Certifications field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Related certifications
   * - **API ID Path**: skills.default.primary.certifications
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  certifications: prismic.KeyTextField;

  /**
   * Certification URL field in *Skills → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to certification
   * - **API ID Path**: skills.default.primary.certification_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  certification_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Projects Count field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Number of projects using this skill
   * - **API ID Path**: skills.default.primary.projects_count
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  projects_count: prismic.NumberField;

  /**
   * Related Projects field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.related_projects[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  related_projects: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimaryRelatedProjectsItem>
  >;

  /**
   * Professional Usage field in *Skills → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: How you've used it professionally
   * - **API ID Path**: skills.default.primary.professional_usage
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  professional_usage: prismic.RichTextField;

  /**
   * Learning Source field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**:  Where/how you learned it
   * - **API ID Path**: skills.default.primary.learning_source
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  learning_source: prismic.KeyTextField;

  /**
   * Currently Learning field in *Skills → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: skills.default.primary.currently_learning
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  currently_learning: prismic.BooleanField;

  /**
   * Next Milestone field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.next_milestone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  next_milestone: prismic.KeyTextField;

  /**
   * Voice Description field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description for voice reading
   * - **API ID Path**: skills.default.primary.voice_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  voice_description: prismic.KeyTextField;

  /**
   * Skill Keywords field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search/voice command keywords
   * - **API ID Path**: skills.default.primary.skill_keywords
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_keywords: prismic.KeyTextField;

  /**
   * Importance Rank field in *Skills → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1-10 for AI prioritization
   * - **API ID Path**: skills.default.primary.importance_rank
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  importance_rank: prismic.NumberField;

  /**
   * Skill Aliases field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Alternative names (e.g., "JS" for JavaScript)
   * - **API ID Path**: skills.default.primary.skill_aliases
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill_aliases: prismic.KeyTextField;

  /**
   * Environment field in *Skills → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.environment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  environment: prismic.SelectField<
    "Client" | "Server" | "Fullstack" | "Mobile" | "Cloud"
  >;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      ContactPageDocument,
      ContactPageDocumentData,
      ContactPageDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      BlogSlice,
      BlogSliceDefaultPrimaryTagsItem,
      BlogSliceDefaultPrimary,
      BlogSliceVariation,
      BlogSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      EducationSlice,
      EducationSliceVariation,
      EducationSliceDefault,
      ExperienceSlice,
      ExperienceSliceDefaultPrimary,
      ExperienceSliceVariation,
      ExperienceSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimaryTechnologiesItem,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimaryRelatedProjectsItem,
      SkillsSliceDefaultPrimary,
      SkillsSliceVariation,
      SkillsSliceDefault,
    };
  }
}
