// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  blog: dynamic(() => import("./Blog")),
  blogposts: dynamic(() => import("./BlogPosts")),
  certification_collection: dynamic(() => import("./CertificationCollection")),
  certifications: dynamic(() => import("./Certifications")),
  contact: dynamic(() => import("./Contact")),
  education: dynamic(() => import("./Education")),
  education_collection: dynamic(() => import("./EducationCollection")),
  experience: dynamic(() => import("./Experience")),
  experience_collection: dynamic(() => import("./ExperienceCollection")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  projects_collection: dynamic(() => import("./ProjectsCollection")),
  skills: dynamic(() => import("./Skills")),
  skills_collection: dynamic(() => import("./SkillsCollection")),
};
